project:
  type: website

website:
  favicon: favicon.png
  title: "Machine Learning con R y Python"
  site-url: https://blogrpy.netlify.app/
  description: "Machine Learning con R y Python"
  margin-header: subscribe.html
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Edimer
      - icon: linkedin
        href: https://co.linkedin.com/in/edimer-david-jaramillo-94a510199 
      - icon: rss
        href: index.xml  
format:
  html:
    theme:
      light: litera
      dark: solar
    css: styles.css
